name: mygym
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.9.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  data_table_2: ^2.6.0
  photo_view: ^0.15.0
  share_plus: ^12.0.0
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # opcional, recomendado

